version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-ubunts4
    tty: true
    stdin_open: true
    working_dir: /app
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    command: ["./node_modules/.bin/env-cmd",  "-e", "production", "node", "dist/apps/backend/main"]
    # command: ["./node_modules/.bin/env-cmd",  "-e", "production", "dist/apps/backend/main"]
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'

volumes:
  mysql-data:
    driver: local
