#==================================================

# Package install Layer

FROM node:18-slim as node_modules

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --non-interactive --frozen-lockfile --production

#==================================================

# Build Layer

FROM node:18-slim as build

WORKDIR /app

# prisma generate に必要
RUN apt-get -qy update && \
  apt-get -qy install \
  openssl --no-install-recommends && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/\*

COPY package.json yarn.lock ./

RUN yarn install --non-interactive --frozen-lockfile

COPY . .

RUN yarn build:api && yarn prisma generate

#==================================================

# Run Layer

# Googleによってメンテンスされている Distroless を使用
FROM gcr.io/distroless/nodejs:18

WORKDIR /app

ENV NODE_ENV=production

# 各レイヤーからcopy
# COPY --from=build --chown=nonroot:nonroot /app/dist /app/dist
# COPY --from=build --chown=nonroot:nonroot /app/.env-cmdrc /app/.env-cmdrc
COPY --from=build /app/dist /app/dist
COPY --from=build /app/.env-cmdrc /app/.env-cmdrc
COPY --from=node_modules /app/node_modules /app/node_modules

# prisma generate で生成したものを copy
# devDependencies が必要なため--from=build から copy する
COPY --from=build /app/node_modules/@prisma/client /app/node_modules/@prisma/client
COPY --from=build /app/node_modules/.prisma/client /app/node_modules/.prisma/client

# 特権ユーザーを使用しないためにDistrolessに用意されているユーザーを使用
# USER nonroot
