#==================================================

# Base image Layer

FROM node:18.4-slim as base

#==================================================

# Package install Layer

FROM base as node_modules

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --non-interactive --frozen-lockfile --production

#==================================================

# Build Layer

FROM base as build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --non-interactive --frozen-lockfile

COPY . .

RUN yarn build:api && yarn prisma generate

#==================================================

# Run Layer
FROM base

WORKDIR /app

ENV NODE_ENV=production

# replace npm in CMD with tini for better kernel signal handling
RUN apt-get update \
  && apt-get -qq install -y --no-install-recommends \
  tini \
  && rm -rf /var/lib/apt/lists/*

# 非root 権限ユーザーの追加
RUN useradd -m myuser && chown -R myuser /app

COPY --from=build /app/dist /app/dist
COPY --from=build /app/.env-cmdrc /app/.env-cmdrc
COPY --from=build /app/prisma /app/prisma
COPY --from=node_modules /app/node_modules /app/node_modules

# prisma generate で生成したものを copy
# devDependencies が必要なため--from=build から copy する
COPY --from=build /app/node_modules/@prisma/client /app/node_modules/@prisma/client
COPY --from=build /app/node_modules/.prisma/client /app/node_modules/.prisma/client

USER myuser
ENTRYPOINT ["/usr/bin/tini", "--"]
